# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2ca02f5d13556b8fbde43ad2e4d901633dd690ff4591b347321382bf5d89e49db5a5180ee4e89499c7e9997d46e31bb95c423037940d565e95da857fe929076

test:
  secret_key_base: 4de0a8b28913066e3288b164124f9fcea2a1afea781e22766307c1cdf06c699e273d3245b894620f0faed39329bbf87124cae994d1e7e09d0d4c86c760476def

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
